spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      dialect.storage_engine: innodb
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        check_nullability: true
  datasource:
    url: ${database.url}
    username: ${database.username}
    driver-class-name: com.mysql.cj.jdbc.Driver