spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      dialect.storage_engine: innodb
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        check_nullability: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order_management_system
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver